# Generated by Django 5.2.3 on 2025-06-15 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(help_text='Nama aktor', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(help_text='Nama genre', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_year', models.IntegerField(help_text='Tahun rilis film', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Judul film', max_length=255)),
                ('rating', models.FloatField(help_text='Rating film')),
                ('votes', models.IntegerField(help_text='Jumlah suara yang diberikan untuk film')),
                ('actor_appearance_count', models.IntegerField(default=0, help_text='Jumlah kemunculan aktor dalam satu tahun')),
                ('genre_appearance_count', models.IntegerField(default=0, help_text='Jumlah kemunculan genre dalam satu tahun')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buin.dimactor')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buin.dimgenre')),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buin.dimtime')),
            ],
        ),
    ]
