# Generated by Django 5.2.3 on 2025-06-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factmovie',
            name='rating',
            field=models.FloatField(default=0, help_text='Rating film'),
        ),
        migrations.AlterField(
            model_name='factmovie',
            name='votes',
            field=models.IntegerField(default=0, help_text='Jumlah suara yang diberikan untuk film'),
        ),
    ]
